version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/sahayata24x7

hooks:
  BeforeInstall:
    - location: Scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: Scripts/set_permissions.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: Scripts/instance_os_dependencies.sh
      timeout: 300
      runas: ubuntu
    - location: Scripts/python_dependencies.sh
      timeout: 300
      runas: root
    - location: Scripts/gunicorn.sh     
      timeout: 300
      runas: ubuntu
    - location: Scripts/nginx.sh         
      timeout: 300
      runas: ubuntu
    - location: Scripts/start_app.sh
      timeout: 300
      runas: ubuntu
